package com.example.myapp.entity;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

/**
 * Represents an immutable audit log entry for a Card.
 *
 * JPA Mapping:
 *  - Maps to the "activity_logs" table
 *  - ID is auto-generated by the database
 *  - card and user are @ManyToOne relationships
 *  - createdAt is set automatically before insert via @PrePersist
 *  - No setters — immutable once recorded
 */
@Entity
@Table(name = "activity_logs")
public class ActivityLog {

    // ─── FIELDS ──────────────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "card_id", nullable = false, updatable = false)
    private Card card;
    
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, updatable = false)
    private AppUser user;

    @Column(nullable = false, length = 200)
    private String action;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    private static final DateTimeFormatter FORMATTER =
                         DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    // ─── JPA REQUIRED NO-ARG CONSTRUCTOR ─────────────────────────────────────

    protected ActivityLog() {}

    // ─── CONSTRUCTOR ─────────────────────────────────────────────────────────

    public ActivityLog(Card card, AppUser user, String action) {
        if (card == null)
            throw new IllegalArgumentException("Card cannot be null");
        if (user == null)
            throw new IllegalArgumentException("User cannot be null");
        if (action == null || action.isBlank())
            throw new IllegalArgumentException("Action cannot be null or blank");
        if (action.length() > 200)
            throw new IllegalArgumentException("Action exceeds 200 character limit");

        this.card   = card;
        this.user   = user;
        this.action = action;
    }

    // ─── JPA LIFECYCLE CALLBACK ───────────────────────────────────────────────

    @PrePersist
    private void prePersist() {
        this.createdAt = LocalDateTime.now();
    }

    // ─── GETTERS — no setters, immutable ─────────────────────────────────────

    public Integer getId()       { return id;     }
    public Card    getCard()     { return card;   }
    public AppUser getUser()     { return user;   }
    public String  getAction()   { return action; }

    public String getCreatedAt() {
        return createdAt.format(FORMATTER);
    }
}