package com.example.myapp.entity;


import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

/**
 * Represents a registered user of the application.
 *
 * JPA Mapping:
 *  - Maps to the "users" table
 *  - ID is auto-generated by the database
 *  - Email is unique at the database level
 *  - createdAt is set automatically before insert via @PrePersist
 */
@Entity
@Table(name = "app_users")
public class AppUser {

    // ─── FIELDS ──────────────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer userId;

    @Column(nullable = false,length = 50)
    private String username;

    @Column(nullable = false, unique = true)  // email must be unique
    private String email;

    @Column(nullable = false)
    private String password;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    private static final DateTimeFormatter FORMATTER =
                         DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    // ─── JPA REQUIRED NO-ARG CONSTRUCTOR ─────────────────────────────────────

    protected AppUser() {}

    // ─── CONSTRUCTOR ─────────────────────────────────────────────────────────
public AppUser(String username, String email, String password) {
    if (username == null || username.isBlank())
        throw new IllegalArgumentException("Username cannot be empty");
    if (username.length() > 50)
        throw new IllegalArgumentException("Username exceeds 50 characters");
    if (email == null || email.isBlank())
        throw new IllegalArgumentException("Email cannot be empty");
    if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"))
        throw new IllegalArgumentException("Invalid email");
    
    this.username = username;
    this.email    = email;
    this.password = password;
}
    

    // ─── JPA LIFECYCLE CALLBACK ───────────────────────────────────────────────

    @PrePersist
    private void prePersist() {
        this.createdAt = LocalDateTime.now();
    }

    // ─── SETTERS ─────────────────────────────────────────────────────────────

    
public void setUsername(String username) {
    if (username == null || username.isBlank())
        throw new IllegalArgumentException("Username cannot be empty");
    if (username.length() > 50)
        throw new IllegalArgumentException("Username exceeds 50 characters");
    this.username = username;
}

public void setEmail(String email) {
    if (email == null || email.isBlank())
        throw new IllegalArgumentException("Email cannot be empty");
    if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"))
        throw new IllegalArgumentException("Invalid email");
    this.email = email;
}

public void setPassword(String password) {
    
    this.password = password;
}


    // ─── GETTERS ─────────────────────────────────────────────────────────────

    public Integer getId()   { return userId;   }
    public String  getUsername() { return username; }
    public String  getEmail()    { return email;    }
    public String getPassword() { return password; }
    public String getCreatedAt() {
        return createdAt.format(FORMATTER);
    }


    // ─── UTILITY ─────────────────────────────────────────────────────────────


    @Override
    public String toString() {
        return String.format("User[id=%d, name=%s, email=%s]",
                              userId, username, email);
    }
}