package com.example.myapp.entity;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

/**
 * Represents a Kanban board inside a Workspace.
 *
 * JPA Mapping:
 *  - Maps to the "boards" table
 *  - ID is auto-generated by the database
 *  - workspace and createdBy are @ManyToOne relationships
 *  - visibility is stored as a STRING enum
 *  - createdAt is set automatically before insert via @PrePersist
 */
@Entity
@Table(name = "boards")
public class Board {

    // ─── ENUM ─────────────────────────────────────────────────────────────────

    public enum Visibility { PRIVATE, WORKSPACE, PUBLIC }

    // ─── FIELDS ──────────────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "workspace_id", nullable = false, updatable = false)
    private Workspace workspace;

    @Column(nullable = false, length = 100)
    private String name;

    @Column(length = 500)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Visibility visibility;
    
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false, updatable = false)
    private AppUser createdBy;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    private static final DateTimeFormatter FORMATTER =
                         DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    // ─── JPA REQUIRED NO-ARG CONSTRUCTOR ─────────────────────────────────────

    protected Board() {}

    // ─── JPA LIFECYCLE CALLBACK ───────────────────────────────────────────────

    @PrePersist
    private void prePersist() {
        this.createdAt = LocalDateTime.now();
        this.description = "";
    }
    
    public Board(Workspace workspace, String boardName, Visibility visibility, AppUser createdBy) {
    if (workspace == null)
        throw new IllegalArgumentException("Workspace cannot be null");
    if (boardName == null || boardName.isBlank())
        throw new IllegalArgumentException("Board name cannot be empty");
    if (boardName.length() > 100)
        throw new IllegalArgumentException("Board name exceeds 100 characters");
    if (visibility == null)
        throw new IllegalArgumentException("Visibility cannot be null");
    if (createdBy == null)
        throw new IllegalArgumentException("Creator cannot be null");
    this.workspace  = workspace;
    this.name       = boardName;
    this.visibility = visibility;
    this.createdBy  = createdBy;
}

public void setName(String boardName) {
    if (boardName == null || boardName.isBlank())
        throw new IllegalArgumentException("Board name cannot be empty");
    if (boardName.length() > 100)
        throw new IllegalArgumentException("Board name exceeds 100 characters");
    this.name = boardName;
}

public void setVisibility(Visibility visibility) {
    if (visibility == null)
        throw new IllegalArgumentException("Visibility cannot be null");
    this.visibility = visibility;
}

public void setDescription(String text) {
    if (text != null && text.length() > 500)
        throw new IllegalArgumentException("Description exceeds 500 characters");
    this.description = text == null ? "" : text;
}

    // ─── GETTERS ─────────────────────────────────────────────────────────────

    public Integer    getId()         { return id;         }
    public Workspace  getWorkspace()  { return workspace;  }
    public String     getName()       { return name;       }
    public Visibility getVisibility() { return visibility; }
    public AppUser       getCreatedBy()  { return createdBy;  }

    public String getDescription() {
        return description;
    }

    public String getCreatedAt() {
        return createdAt.format(FORMATTER);
    }
}