package com.example.myapp.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;


/**
 * Represents a card (ticket) on a Kanban board.
 *
 * JPA Mapping:
 *  - Maps to the "cards" table
 *  - ID is auto-generated by the database
 *  - ticketId is generated after insert by calling generateTicketId()
 *    manually in CardService (not via a JPA lifecycle callback)
 *  - lane and createdBy are @ManyToOne relationships
 *  - createdAt is set automatically before insert via @PrePersist
 */
@Entity
@Table(name = "cards")
public class Card {

    // ─── FIELDS ──────────────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "ticket_id", unique = true)
    private String ticketId;  // set after insert e.g. "TKT-0001"
    
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lane_id", nullable = false)
    private Lane lane;

    @Column(nullable = false, length = 150)
    private String title;

    @Column(length = 500)
    private String description;  // optional

    @Column(nullable = false)
    private Integer position;

    @Column(name = "due_date")
    private LocalDate dueDate;  // optional

    @Column(name = "is_archived", nullable = false)
    private boolean isArchived;
    
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false, updatable = false)
    private AppUser createdBy;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    private static final DateTimeFormatter FORMATTER =
                         DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    // ─── JPA REQUIRED NO-ARG CONSTRUCTOR ─────────────────────────────────────

    protected Card() {}

    // ─── CONSTRUCTOR ─────────────────────────────────────────────────────────

    public Card(Lane lane, String title, Integer position, AppUser createdBy) {
        if (lane == null)
            throw new IllegalArgumentException("Lane cannot be null");
        if (title == null || title.isBlank())
            throw new IllegalArgumentException("Title cannot be empty");
        if (title.length() > 150)
            throw new IllegalArgumentException("Title exceeds 150 characters");
        if (position == null || position < 0)
            throw new IllegalArgumentException("Position cannot be null or negative");
        if (createdBy == null)
            throw new IllegalArgumentException("Creator cannot be null");

        this.lane      = lane;
        this.title     = title;
        this.position  = position;
        this.createdBy = createdBy;
    }

    // ─── JPA LIFECYCLE CALLBACKS ──────────────────────────────────────────────

    @PrePersist
    private void prePersist() {
        this.createdAt   = LocalDateTime.now();
        this.isArchived  = false;
        this.dueDate     = null;
        this.description = "";
    }

    public void generateTicketId() {
        this.ticketId = String.format("TKT-%04d", id);
    }

    // ─── SETTERS ─────────────────────────────────────────────────────────────

    public void setTitle(String title) {
        if (title == null || title.isBlank())
            throw new IllegalArgumentException("Title cannot be empty");
        if (title.length() > 150)
            throw new IllegalArgumentException("Title exceeds 150 characters");
        this.title = title;
    }

    public void setDescription(String text) {
        if(text!=null && text.length()>500){
            throw new IllegalArgumentException("Description exceeds 500 characters");
        }
        this.description = text;  // null accepted — clears description
    }

    public void setDueDate(LocalDate date) {
        if (date == null) { this.dueDate = null; return; }
        if (date.isBefore(createdAt.toLocalDate()))
            throw new IllegalArgumentException("Due date cannot be before creation date");
        this.dueDate = date;
    }

    public void setLane(Lane lane) {
        if (lane == null)
            throw new IllegalArgumentException("Lane cannot be null");
        this.lane = lane;
    }

    public void setPosition(Integer position) {
        if (position == null || position < 0)
            throw new IllegalArgumentException("Position cannot be null or negative");
        this.position = position;
    }

    public void archived()   { this.isArchived = true;  }
    public void unarchived() { this.isArchived = false; }

    // ─── GETTERS ─────────────────────────────────────────────────────────────

    public Integer getId()        { return id;              }
    public String  getTicketId()  { return ticketId;        }
    public Lane    getLane()      { return lane;            }
    public Integer getLaneId()    { return lane.getId();    }
    public Integer getPosition()  { return position;        }
    public String  getTitle()     { return title;           }
    public AppUser getCreatedBy() { return createdBy;       }
    public boolean isArchived()   { return isArchived;      }

    public String getDescription() {
        return description;
    }

    public String getDueDate() {
        if (dueDate == null) return "No Date";
        return dueDate.format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
    }

    public String getCreatedAt() {
        return createdAt.format(FORMATTER);
    }
}