package com.example.myapp.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

/**
 * Represents a single item inside a Checklist.
 *
 * JPA Mapping:
 *  - Maps to the "checklist_items" table
 *  - checklist is a @ManyToOne relationship
 *  - isDone defaults to false via @PrePersist
 *  - ID is auto-generated by the database
 */
@Entity
@Table(name = "checklist_items")
public class ChecklistItem {

    // ─── FIELDS ──────────────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    
    @JsonIgnore  // prevents infinite recursion when serializing to JSON
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "checklist_id", nullable = false)
    private Checklist checklist;

    @Column(nullable = false, length = 200)
    private String content;

    @Column(name = "is_done", nullable = false)
    private boolean isDone;

    @Column(name = "position", nullable = false)
    private Integer position;

    // ─── JPA REQUIRED NO-ARG CONSTRUCTOR ─────────────────────────────────────

    protected ChecklistItem() {}

    // ─── JPA LIFECYCLE CALLBACK ───────────────────────────────────────────────

    @PrePersist
    private void prePersist() {
        this.isDone = false;  // items start as incomplete
    }

    // ─── CONSTRUCTOR ─────────────────────────────────────────────────────────

    public ChecklistItem(Checklist checklist, String content, Integer position) {
        if (checklist == null)
            throw new IllegalArgumentException("Checklist cannot be null");
        if (content == null || content.isBlank())
            throw new IllegalArgumentException("Content cannot be empty");
        if (content.length() > 200)
            throw new IllegalArgumentException("Content exceeds 200 characters");
        if (position == null || position < 0)
            throw new IllegalArgumentException("Position cannot be null or negative");

        this.checklist = checklist;
        this.content   = content;
        this.position  = position;
    }

    // ─── SETTERS ─────────────────────────────────────────────────────────────

    public void setContent(String text) {
        if (text == null || text.isBlank())
            throw new IllegalArgumentException("Content cannot be empty");
        if (text.length() > 200)
            throw new IllegalArgumentException("Content exceeds 200 characters");
        this.content = text;
    }

    public void setPosition(Integer position) {
        if (position == null || position < 0)
            throw new IllegalArgumentException("Position cannot be null or negative");
        this.position = position;
    }

    public void markDone()   { this.isDone = true;  }
    public void markUndone() { this.isDone = false; }

    // ─── GETTERS ─────────────────────────────────────────────────────────────

    public Integer   getId()          { return id;        }
    public Checklist getChecklist()   { return checklist; }
    public String    getContent()     { return content;   }
    public Integer   getPosition()    { return position;  }
    public boolean   isDone()         { return isDone;    }
}