package com.example.myapp.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a checklist on a Card.
 *
 * JPA Mapping:
 *  - Maps to the "checklists" table
 *  - card is a @ManyToOne relationship
 *  - ID is auto-generated by the database
 */
@Entity
@Table(name = "checklists")
public class Checklist {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    
    @JsonIgnore  // prevents infinite recursion when serializing to JSON
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "card_id", nullable = false)
    private Card card;

    @Column(nullable = false, length = 100)
    private String title;

    protected Checklist() {}

    public Checklist(Card card, String title) {
        if (card == null)
            throw new IllegalArgumentException("Card cannot be null");
        if (title == null || title.isBlank())
            throw new IllegalArgumentException("Checklist title cannot be empty");
        if (title.length() > 100)
            throw new IllegalArgumentException("Checklist title exceeds 100 characters");

        this.card  = card;
        this.title = title;
    }

    public void setTitle(String title) {
        if (title == null || title.isBlank())
            throw new IllegalArgumentException("Checklist title cannot be empty");
        if (title.length() > 100)
            throw new IllegalArgumentException("Checklist title exceeds 100 characters");
        this.title = title;
    }

    public Integer getId()    { return id;    }
    public Card    getCard()  { return card;  }
    public String  getTitle() { return title; }
}