package com.example.myapp.entity;


import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

/**
 * Represents a workspace — the top-level container for boards and members.
 *
 * JPA Mapping:
 *  - Maps to the "workspaces" table
 *  - ID is auto-generated by the database
 *  - createdBy is a @ManyToOne relationship to User
 *  - createdAt is set automatically before insert via @PrePersist
 */
@Entity
@Table(name = "workspaces")
public class Workspace {

    // ─── FIELDS ──────────────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(nullable = false, length = 100)
    private String name;

    @Column(length = 500)
    private String description;
    
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false, updatable = false)
    private AppUser createdBy;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    private static final DateTimeFormatter FORMATTER =
                         DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    // ─── JPA REQUIRED NO-ARG CONSTRUCTOR ─────────────────────────────────────

    protected Workspace() {}
    // ─── JPA LIFECYCLE CALLBACK ───────────────────────────────────────────────

    @PrePersist
    private void prePersist() {
        this.createdAt = LocalDateTime.now();
        this.description = "";
    }
    public Workspace(String workspaceName, AppUser createdBy) {
    if (workspaceName == null || workspaceName.isBlank())
        throw new IllegalArgumentException("Workspace name cannot be empty");
    if (workspaceName.length() > 100)
        throw new IllegalArgumentException("Name exceeds 100 characters");
    if (createdBy == null)
        throw new IllegalArgumentException("Creator cannot be null");
    this.name      = workspaceName;
    this.createdBy = createdBy;
}

public void setName(String workspaceName) {
    if (workspaceName == null || workspaceName.isBlank())
        throw new IllegalArgumentException("Workspace name cannot be empty");
    if (workspaceName.length() > 100)
        throw new IllegalArgumentException("Name exceeds 100 characters");
    this.name = workspaceName;
}

public void setDescription(String text) {
    if (text != null && text.length() > 500)
        throw new IllegalArgumentException("Description exceeds 500 characters");
    this.description = text == null ? "" : text;
}

    // ─── GETTERS ─────────────────────────────────────────────────────────────

    public Integer getId()        { return id;        }
    public String  getName()      { return name;      }
    public AppUser    getCreatedBy() { return createdBy; }

    public String getDescription() {
        return description;
    }

    public String getCreatedAt() {
        return createdAt.format(FORMATTER);
    }
}