package com.example.myapp.entity;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Represents the membership of a User in a Workspace.
 *
 * JPA Mapping:
 *  - Maps to the "workspace_members" table
 *  - ID is auto-generated by the database
 *  - workspace and user are @ManyToOne relationships
 *  - role is stored as a STRING enum
 *  - joinedAt is set automatically before insert via @PrePersist
 */
@Entity
@Table(name = "workspace_members", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"workspace_id", "user_id"})
})
public class WorkspaceMember {

    // ─── ENUM ─────────────────────────────────────────────────────────────────

    public enum Role { OWNER,ADMIN, MEMBER }

    // ─── FIELDS ──────────────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    
    @JsonIgnore  // prevents infinite recursion when serializing to JSON
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "workspace_id", nullable = false, updatable = false)
    private Workspace workspace;
    
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, updatable = false)
    private AppUser user;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Role role;

    @Column(name = "joined_at", nullable = false, updatable = false)
    private LocalDateTime joinedAt;

    private static final DateTimeFormatter FORMATTER =
                         DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    // ─── JPA REQUIRED NO-ARG CONSTRUCTOR ─────────────────────────────────────

    protected WorkspaceMember() {}

    // ─── JPA LIFECYCLE CALLBACK ───────────────────────────────────────────────

    @PrePersist
    private void prePersist() {
        this.joinedAt = LocalDateTime.now();
    }
    
    public WorkspaceMember(Workspace workspace, AppUser user, Role role) {
    if (workspace == null)
        throw new IllegalArgumentException("Workspace cannot be null");
    if (user == null)
        throw new IllegalArgumentException("User cannot be null");
    if (role == null)
        throw new IllegalArgumentException("Role cannot be null");
    this.workspace = workspace;
    this.user      = user;
    this.role      = role;
}

public void setRole(Role newRole) {
    if (newRole == null)
        throw new IllegalArgumentException("Role cannot be null");
    this.role = newRole;
}

    // ─── GETTERS ─────────────────────────────────────────────────────────────

    public Integer   getId()        { return id;        }
    public Workspace getWorkspace() { return workspace; }
    public AppUser   getUser()      { return user;      }
    public Role      getRole()      { return role;      }

    public String getJoinedAt() {
        return joinedAt.format(FORMATTER);
    }
}